type GenericTeamScoreboard = {
	[key in Team]: number
}

type GenericUsernameScoreboard = {
	[key in string]: number
}

enum Team {
	AQUA = "AQUA",
	BLUE = "BLUE",
	CYAN = "CYAN",
	GREEN = "GREEN",
	LIME = "LIME",
	ORANGE = "ORANGE",
	PINK = "PINK",
	PURPLE = "PURPLE",
	RED = "RED",
	YELLOW = "YELLOW",
	SPECTATORS = "SPECTATORS",
	NONE = "NONE",
	ANY = "",
}

enum Game {
	MG_ACE_RACE = "MG_ACE_RACE",
	MG_PARKOUR_WARRIOR = "MG_PARKOUR_WARRIOR",
	MG_FOOT_RACE = "MG_FOOT_RACE",
	MG_ROCKET_SPLEEF_OLD = "MG_ROCKET_SPLEEF_OLD",
	MG_LOCKOUT_BINGO = "MG_LOCKOUT_BINGO",
	MG_HOLE_IN_THE_WALL = "MG_HOLE_IN_THE_WALL",
	MG_SKYBLOCKLE = "MG_SKYBLOCKLE",
	MG_TGTTOSAWAF = "MG_TGTTOSAWAF",
	MG_BATTLE_BOX = "MG_BATTLE_BOX",
	MG_BUILD_MART = "MG_BUILD_MART",
	MG_BINGO_BUT_FAST = "MG_BINGO_BUT_FAST",
	MG_SANDS_OF_TIME = "MG_SANDS_OF_TIME",
	MG_PARKOUR_TAG = "MG_PARKOUR_TAG",
	MG_SKY_BATTLE = "MG_SKY_BATTLE",
	MG_GRID_RUNNERS = "MG_GRID_RUNNERS",
	MG_ROCKET_SPLEEF = "MG_ROCKET_SPLEEF",
	MG_MELTDOWN = "MG_MELTDOWN",
	ANY = "",
}

enum HOFGame {
	// `Game` enum
	MG_ACE_RACE = "MG_ACE_RACE",
	MG_PARKOUR_WARRIOR = "MG_PARKOUR_WARRIOR",
	MG_FOOT_RACE = "MG_FOOT_RACE",
	MG_ROCKET_SPLEEF_OLD = "MG_ROCKET_SPLEEF_OLD",
	MG_LOCKOUT_BINGO = "MG_LOCKOUT_BINGO",
	MG_HOLE_IN_THE_WALL = "MG_HOLE_IN_THE_WALL",
	MG_SKYBLOCKLE = "MG_SKYBLOCKLE",
	MG_TGTTOSAWAF = "MG_TGTTOSAWAF",
	MG_BATTLE_BOX = "MG_BATTLE_BOX",
	MG_BUILD_MART = "MG_BUILD_MART",
	MG_BINGO_BUT_FAST = "MG_BINGO_BUT_FAST",
	MG_SANDS_OF_TIME = "MG_SANDS_OF_TIME",
	MG_PARKOUR_TAG = "MG_PARKOUR_TAG",
	MG_SKY_BATTLE = "MG_SKY_BATTLE",
	MG_GRID_RUNNERS = "MG_GRID_RUNNERS",
	MG_ROCKET_SPLEEF = "MG_ROCKET_SPLEEF",
	MG_MELTDOWN = "MG_MELTDOWN",
	ANY = "",

	// Hall of Fame specific "games"
	GLOBAL_STATISTICS = "GLOBAL_STATISTICS",
	LEGACY_STATISTICS = "LEGACY_STATISTICS",
}

export { GenericTeamScoreboard, GenericUsernameScoreboard, Team, Game, HOFGame }
